language: node_js
node_js:
  - "node"
  - "6"
sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
script:
  - xvfb-run npm test
  - xvfb-run npm run test:integration
before_script:
  - npm install firebase-tools
  - npm install
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
notifications:
  email:
    on_failure: change
    on_success: change
